import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary": "#303030",
        "tertiary-container": "#919191",
        "surface-dim": "#121414",
        "outline": "#8c90a1",
        "inverse-primary": "#0058cb",
        "error-container": "#93000a",
        "secondary-fixed": "#e9ddff",
        "on-secondary-fixed": "#23005c",
        "tertiary-fixed-dim": "#c6c6c6",
        "primary": "#b0c6ff",
        "on-background": "#e3e2e2",
        "on-primary-fixed": "#001945",
        "on-tertiary-container": "#2a2a2a",
        "inverse-surface": "#e3e2e2",
        "on-primary-fixed-variant": "#00429c",
        "surface-container-low": "#1b1c1c",
        "surface-container": "#1f2020",
        "on-secondary-container": "#c4abff",
        "secondary-container": "#571bc1",
        "tertiary": "#c6c6c6",
        "surface": "#121414",
        "on-surface": "#e3e2e2",
        "surface-bright": "#383939",
        "error": "#ffb4ab",
        "on-primary-container": "#002661",
        "on-tertiary-fixed": "#1b1b1b",
        "surface-container-high": "#292a2a",
        "inverse-on-surface": "#303031",
        "surface-container-lowest": "#0d0e0f",
        "surface-container-highest": "#343535",
        "secondary-fixed-dim": "#d0bcff",
        "surface-variant": "#343535",
        "on-tertiary-fixed-variant": "#474747",
        "on-error": "#690005",
        "primary-fixed-dim": "#b0c6ff",
        "secondary": "#d0bcff",
        "background": "#121414",
        "on-secondary": "#3c0091",
        "on-secondary-fixed-variant": "#5516be",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#d9e2ff",
        "surface-tint": "#b0c6ff",
        "on-surface-variant": "#c2c6d8",
        "outline-variant": "#424655",
        "primary-container": "#568dff",
        "on-primary": "#002d6f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1200px",
        "margin-desktop": "48px",
        base: "8px",
        gutter: "24px",
        "section-gap": "80px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-geist-sans)"],
        "label-sm": ["var(--font-geist-sans)"],
        mono: ["var(--font-geist-sans)"],
        display: ["var(--font-geist-sans)"],
        "headline-md": ["var(--font-geist-sans)"],
        "headline-lg": ["var(--font-geist-sans)"],
        "label-md": ["var(--font-geist-sans)"],
        "body-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        mono: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        display: ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};

export default config;
